"""Markdown generation: one README per language, sections in the configured order."""

from __future__ import annotations

from .config import Loc

HEADER = ("<!--\n  This file is GENERATED by scripts/build.py from profile.toml.\n"
          "  Edit profile.toml instead: manual changes here are overwritten.\n-->\n")

# Sections that get an SVG heading (the banner, links and footer stand alone).
HEADED = ("about", "stack", "skills", "projects", "vitals")


def asset(lang: str, name: str, theme: str) -> str:
    return f"assets/generated/{lang}/{name}-{theme}.svg"


def picture(dark: str, light: str, alt: str, width: str = "100%") -> str:
    size = f' width="{width}"' if width else ""
    return (
        "<picture>"
        f'<source media="(prefers-color-scheme: dark)" srcset="{dark}">'
        f'<source media="(prefers-color-scheme: light)" srcset="{light}">'
        f'<img src="{dark}"{size} alt="{alt}">'
        "</picture>"
    )


def generated(lang: str, name: str, alt: str, width: str = "100%") -> str:
    return picture(asset(lang, name, "dark"), asset(lang, name, "light"), alt, width)


def _banner(cfg, loc, lang, ctx):
    """A ready-made image when [banner] names one, otherwise the generated header."""
    b = cfg.get("banner", {})
    if b.get("dark"):
        alt = loc(b.get("alt", cfg.profile["name"]))
        return f'<div align="center">\n\n{picture(b["dark"], b.get("light", b["dark"]), alt)}\n\n</div>'
    return generated(lang, "header", cfg.profile["name"])


def _links(cfg, loc, lang, ctx):
    items = [f'<a href="{link["url"]}">{loc(link["label"])}</a>' for link in cfg.get("links", [])]
    opts = cfg.get("links_options", {})
    if opts.get("language_switch", True):
        names = cfg.profile.get("language_names", {})
        items += [f'<a href="{cfg.readme_name(o)}">{names.get(o, o).lower()}</a>'
                  for o in cfg.languages if o != lang]
    if opts.get("visitor_counter"):
        items.append(f'<img src="https://komarev.com/ghpvc/?username={cfg.username}'
                     f'&style=flat-square&color=30363d&label=views" alt="views" align="center">')
    return f'<p align="center"><sub>{" &nbsp;·&nbsp; ".join(items)}</sub></p>' if items else ""


def _about(cfg, loc, lang, ctx):
    a = cfg.get("about", {})
    out = [loc(a.get("intro", "")).strip(), ""]
    for point in a.get("points", []):
        icon = f'{point["icon"]} ' if point.get("icon") else ""
        out.append(f"- {icon}{loc(point['text'])}")
    return "\n".join(out)


def _stack(cfg, loc, lang, ctx):
    st = cfg.get("stack", {})
    out = []
    if st.get("icons"):
        # %2C, not ",": srcset treats commas as candidate separators and
        # would cut the URL after the first icon.
        base = (f'https://skillicons.dev/icons?i={"%2C".join(st["icons"])}'
                f'&perline={st.get("per_line", 15)}')
        icons = picture(f"{base}&theme=dark", f"{base}&theme=light", ", ".join(st["icons"]), width="")
        out.append(f'<p align="center"><a href="https://skillicons.dev">{icons}</a></p>')
    if st.get("extra"):
        out.append(generated(lang, "stack", ", ".join(map(loc, st["extra"]))))
    return "\n\n".join(out)


def _skills(cfg, loc, lang, ctx):
    return generated(lang, "genome", loc(cfg["headings"]["skills"]))


def _projects(cfg, loc, lang, ctx):
    gh = ctx["gh"]
    cells = []
    for p in cfg.get("projects", []):
        repo = gh.repos.get(p["repo"].lower())
        # Offline builds cannot tell private repos apart: assume public.
        fallback = None if gh.online else f'https://github.com/{cfg.username}/{p["repo"]}'
        url = p.get("url") or (repo["html_url"] if repo else fallback)
        img = generated(lang, f'project-{p["repo"]}', p["repo"], width="49%")
        cells.append(f'<a href="{url}">{img}</a>' if url else img)
    # Plain inline images rather than a <table>: GitHub draws table borders.
    return '<p align="center">\n' + "\n".join(cells) + "\n</p>"


def _vitals(cfg, loc, lang, ctx):
    return generated(lang, "vitals", loc(cfg["headings"]["vitals"]))


def _footer(cfg, loc, lang, ctx):
    text = loc(cfg.get("footer", {}).get("text", ""), username=cfg.username, name=cfg.profile["name"])
    return f'<p align="center"><sub>{text}</sub></p>' if text else ""


BUILDERS = {
    "banner": _banner, "links": _links, "about": _about, "stack": _stack,
    "skills": _skills, "projects": _projects, "vitals": _vitals, "footer": _footer,
}


def render(cfg, lang: str, gh) -> str:
    loc: Loc = cfg.loc(lang)
    ctx = {"gh": gh}
    parts = []
    for section in cfg.profile.get("sections", list(BUILDERS)):
        if section not in BUILDERS:
            raise SystemExit(f"profile.toml: unknown section '{section}' (valid: {', '.join(BUILDERS)})")
        block = BUILDERS[section](cfg, loc, lang, ctx)
        if not block:
            continue
        if section in HEADED:
            heading = generated(lang, f"heading-{section}", loc(cfg["headings"][section]))
            block = f"{heading}\n\n{block}"
        parts.append(block)
    return HEADER + "\n" + "\n\n<br>\n\n".join(parts) + "\n"


def headed_sections(cfg) -> list[str]:
    """Sections that need a heading SVG, in display order (drives numbering)."""
    return [s for s in cfg.profile.get("sections", []) if s in HEADED]
